[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:nextjs]
directory=/var/www/frontend
command=npm start
autostart=true
autorestart=true
environment=PORT=3000,NODE_ENV=production